export const conditionDescriptions = {
  Blinded: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Blinded',
  Charmed: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Charmed',
  Deafened: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Deafened',
  Exhaustion: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Exhaustion',
  Frightened: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Frightened',
  Grappled: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Grappled',
  Incapacitated: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Incapacitated',
  Invisible: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Invisible',
  Paralyzed: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Paralyzed',
  Petrified: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Petrified',
  Poisoned: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Poisoned',
  Prone: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Prone',
  Restrained: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Restrained',
  Stunned: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Stunned',
  Unconscious: 'https://www.dndbeyond.com/sources/basic-rules/appendix-a-conditions#Unconscious',
};

export default [
  'Blinded',
  'Charmed',
  'Deafened',
  'Exhaustion',
  'Frightened',
  'Grappled',
  'Incapacitated',
  'Invisible',
  'Paralyzed',
  'Petrified',
  'Poisoned',
  'Prone',
  'Restrained',
  'Stunned',
  'Unconscious',
];
